import { Bookmark, Category } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-work', name: 'Work', color: '#3b82f6', isDefault: true },
  { id: 'cat-dev', name: 'Development', color: '#10b981', isDefault: true },
  { id: 'cat-finance', name: 'Finance', color: '#f59e0b', isDefault: true },
  { id: 'cat-social', name: 'Social', color: '#ec4899', isDefault: true },
  { id: 'cat-shopping', name: 'Shopping', color: '#8b5cf6', isDefault: true },
  { id: 'cat-entertainment', name: 'Entertainment', color: '#ef4444', isDefault: true },
  { id: 'cat-personal', name: 'Personal', color: '#06b6d4', isDefault: true },
];

export const INITIAL_BOOKMARKS: Bookmark[] = [
  {
    id: 'bm-1',
    title: 'GitHub',
    url: 'https://github.com',
    category: 'Development',
    description: 'Code hosting and collaboration platform for software projects.',
    isFavorite: true,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 1000000,
  },
  {
    id: 'bm-2',
    title: 'Gmail',
    url: 'https://mail.google.com',
    category: 'Work',
    description: 'Personal and professional email communications.',
    isFavorite: true,
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: 'bm-3',
    title: 'Notion',
    url: 'https://notion.so',
    category: 'Work',
    description: 'Connected workspace for wiki, docs, and project management.',
    isFavorite: true,
    createdAt: Date.now() - 800000,
    updatedAt: Date.now() - 800000,
  },
  {
    id: 'bm-4',
    title: 'ChatGPT',
    url: 'https://chatgpt.com',
    category: 'Development',
    description: 'AI language model interface for assistant and research.',
    isFavorite: false,
    createdAt: Date.now() - 700000,
    updatedAt: Date.now() - 700000,
  },
  {
    id: 'bm-5',
    title: 'YouTube',
    url: 'https://youtube.com',
    category: 'Entertainment',
    description: 'Video sharing, tutorials, and music streaming.',
    isFavorite: false,
    createdAt: Date.now() - 600000,
    updatedAt: Date.now() - 600000,
  },
  {
    id: 'bm-6',
    title: 'LinkedIn',
    url: 'https://linkedin.com',
    category: 'Social',
    description: 'Professional networking platform.',
    isFavorite: false,
    createdAt: Date.now() - 500000,
    updatedAt: Date.now() - 500000,
  },
  {
    id: 'bm-7',
    title: 'Google Drive',
    url: 'https://drive.google.com',
    category: 'Work',
    description: 'Cloud storage and document collaboration.',
    isFavorite: false,
    createdAt: Date.now() - 400000,
    updatedAt: Date.now() - 400000,
  },
];

export const INITIAL_DEMO_VAULT_ITEMS = [
  {
    id: 'pwd-1',
    websiteName: 'GitHub',
    websiteUrl: 'https://github.com/login',
    username: 'dev.user@example.com',
    password: 'xK9#mQ$2vP!8zL5n',
    notes: 'Developer account API keys and primary repositories.',
    category: 'Development',
    isFavorite: true,
    createdAt: Date.now() - 1000000,
    updatedAt: Date.now() - 1000000,
  },
  {
    id: 'pwd-2',
    websiteName: 'Google Account',
    websiteUrl: 'https://accounts.google.com',
    username: 'arnav.gupta@example.com',
    password: 'gH$7wN*1kX#9yT3m',
    notes: 'Primary email and Workspace login.',
    category: 'Work',
    isFavorite: true,
    createdAt: Date.now() - 900000,
    updatedAt: Date.now() - 900000,
  },
  {
    id: 'pwd-3',
    websiteName: 'Notion',
    websiteUrl: 'https://www.notion.so/login',
    username: 'arnav.gupta@example.com',
    password: 'nT!4vR%8pB@2wM6q',
    notes: 'Workspace documentation login.',
    category: 'Work',
    isFavorite: false,
    createdAt: Date.now() - 800000,
    updatedAt: Date.now() - 800000,
  },
  {
    id: 'pwd-4',
    websiteName: 'Vercel',
    websiteUrl: 'https://vercel.com/login',
    username: 'dev.user@example.com',
    password: 'vC&9xK!3mL#7pQ2z',
    notes: 'Production deployments and DNS records.',
    category: 'Development',
    isFavorite: false,
    createdAt: Date.now() - 700000,
    updatedAt: Date.now() - 700000,
  },
];
